version: '3.3'
services:
    solr:
        build: ./solr/
        ports:
            - 8983:8983
    webapp:
        image: php:apache
        ports:
            - 80:80
        volumes:
            - .:/var/www/html/
